apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hearth
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hearth
subjects:
  - kind: ServiceAccount
    name: hearth
    namespace: hearth
