apiVersion: apps/v1
kind: Deployment
metadata:
  name: hearth
  namespace: hearth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hearth
  template:
    metadata:
      labels:
        app: hearth
    spec:
      serviceAccountName: hearth
      containers:
        - name: hearth
          image: quay.io/rh_perfscale/hearth:latest
          imagePullPolicy: Always
          env:
            - name: HEARTH_NAMESPACE
              value: hearth
            - name: HEARTH_SECRETS_NAMESPACE
              value: psap-secrets
          ports:
            - containerPort: 8080
              name: healthz
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
