apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - sa.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - secrets-role.yaml
  - secrets-rolebinding.yaml
  - imagestream.yaml
  - workload-priorities.yaml
  - deployment.yaml
