apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hearth-secrets
  namespace: psap-secrets
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "patch"]
