apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hearth-secrets
  namespace: psap-secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hearth-secrets
subjects:
  - kind: ServiceAccount
    name: hearth
    namespace: hearth
