apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hearth
  namespace: openshift-gitops
spec:
  project: hearth
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jqPathExpressions:
        - .spec.template.spec.containers[].image
        - .spec.template.metadata.annotations
  source:
    repoURL: https://github.com/openshift-psap/hearth.git
    targetRevision: main
    path: deploy
  destination:
    server: https://kubernetes.default.svc
    namespace: hearth
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
